spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:"
    username: sa
    password:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50

# Mapper Setting
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml    # mybatis mapper 위치 설정
  type-aliases-package: com.spring.template.vo        # xml 파일 result type에 패키지명을 생략할 수 있도록 alias 설정
  configuration:
    map-underscore-to-camel-case: true              # model 프로퍼티 camal case 설정

#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@{IP}:{PORT}:{SERVICE_NAME}
#    username: {ID}
#    password: {PASSWORD}
#    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 50
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      url: jdbc:log4jdbc:oracle:thin:@{IP}:{PORT}:{SERVICE_NAME}
#      username: { ID }
#      password: { PASSWORD }
#      hikari:
#        auto-commit: false
#        connection-test-query: SELECT 1
#        minimum-idle: 10
#        maximum-pool-size: 50
#        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
#        pool-name: pool-tester
